# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  gl_renderer_config = debug

else ifeq ($(config),release)
  gl_renderer_config = release

else ifeq ($(config),dist)
  gl_renderer_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := gl_renderer

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

gl_renderer:
ifneq (,$(gl_renderer_config))
	@echo "==== Building gl_renderer ($(gl_renderer_config)) ===="
	@${MAKE} --no-print-directory -C . -f gl_renderer.make config=$(gl_renderer_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f gl_renderer.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   gl_renderer"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"